build-vinavaCloud:
  stage: build
  script:
    - bash build.sh uat
    - docker build --build-arg profile=uat . -t registry.gitlab.com/vinava/pofo/pofo-api
    - docker push registry.gitlab.com/vinava/pofo/pofo-api
  only:
    - master

run-vinavaCloud:
  stage: deploy
  script:
    - docker rm -f pofo-stage-api || true
    - docker run -d --restart=always --name pofo-stage-api --expose 5555 -e VIRTUAL_HOST=pofo-stage-api.vinavalabs.com -t registry.gitlab.com/vinava/pofo/pofo-api:latest uat
  only:
    - master

check-vinavaCloud:
  stage: .post
  script:
    - bash checkUp.sh
  only:
    - master
    